# Prometheus Configuration for AIMS Web Application
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'aims-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules for recording and alerting
rule_files:
  - "alerting_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # AIMS Web Application Frontend
  - job_name: 'aims-web-frontend'
    static_configs:
      - targets: ['web:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # AIMS API Backend
  - job_name: 'aims-api-backend'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # System metrics from node-exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Container metrics from cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'

  # Nginx metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics (if using Redis)
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Database metrics (SQLite monitoring via custom exporter)
  - job_name: 'database-exporter'
    static_configs:
      - targets: ['db-exporter:9187']
    scrape_interval: 60s
    scrape_timeout: 15s

  # Blackbox monitoring for external endpoints
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://aims.com
          - https://api.aims.com/health
          - https://staging.aims.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom application metrics
  - job_name: 'aims-custom-metrics'
    static_configs:
      - targets: ['metrics-collector:8090']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/custom-metrics'

# Remote write configuration (for long-term storage)
remote_write:
  - url: "https://monitoring.aims.com/api/v1/write"
    basic_auth:
      username: prometheus
      password: secure_password
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Performance tuning
scrape_configs_defaults:
  scrape_interval: 15s
  scrape_timeout: 10s
  honor_labels: false
  honor_timestamps: true
  scheme: http
  follow_redirects: true
  enable_http2: true